### ISSUE TITLE
Meson: build.ninja in build directory

### ISSUE THREAD

**Issue by gauteh** [johnsyweb/vim-makeshift#17]
Hi,

I'm using meson, how can I get Makeshift to detect build.ninja in a build sub-dir and set build command to ninja -C build ?

**Comment by johnsyweb** [comment]
Hi @gauteh,

I'm not familiar with how The Meson Build system works, but [adding a new build system](
https://github.com/johnsyweb/vim-makeshift#adding-a-new-build-system) to Makeshift works by adding a dictionary to your vimrc.

Note that Makeshift [works by looking for known build files in the current working directory upwards](https://github.com/johnsyweb/vim-makeshift#how-it-works) (and not looking in sub-directories).

So... I think you want to add the following to your vimrc:

```vim
let g:makeshift_systems = {
    \'meson.build': 'ninja -C build',
    \}
```

**Comment by gauteh** [comment]
Hi, thanks that works.
